main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  # All the intermediate files will be copied to this directory at the end of the run.
  # Set this to null if you are running in prod
  project_name: nyc_airbnb
  experiment_name: development
  steps: all
etl:
  sample: "sample1.csv"
  min_price: 10  # dollars
  max_price: 350  # dollars
data_check:
  kl_threshold: 0.2
modeling:
  random_seed: 42
  stratify_by: neighbourhood_group
  val_size: 0.2
  max_tfidf_features: 5
  random_forest:
    n_estimators: 200
    max_depth: 50
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    # Here -1 means all available cores
    n_jobs: -1
    criterion: squared_error
    max_features: 0.5
    # DO not change the following
    oob_score: true